name: E-Commerce CI

on:
  push:
    branches:
      - main
      - dev
      - 'feature/**'
  pull_request:
    branches:
      - main
      - dev

jobs:
  lint-test-security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
          cache-dependency-path: |
            requirements.txt
            requirements-dev.txt

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest flake8 black isort mypy bandit

      # --- Code Style ---
      - name: Lint with flake8
        run: flake8 src/ tests/

      - name: Check formatting with Black
        run: black --check src/ tests/

      - name: Check imports with isort
        run: isort --check-only src/ tests/

      - name: Static type checking with mypy
        run: mypy src/

      # --- Security ---
      - name: Security scan with bandit
        run: bandit -q -r src/

      # --- Tests ---
      - name: Run Unit Tests
        run: pytest tests/ -v --tb=short
